language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=^8 COVERAGE=1
    - php: 7.2
      env: TYPO3_VERSION=^8
env:
  global:
    - CC_TEST_REPORTER_ID: d3719b289927b05bd9152291beb62d8e25d9e66f347011cbe9d7922885f29b60
    - secure: S8QheEMVpSRsPPIhYQZ4tUCTbxpM7csZ0GydJaPY8p/FAEnZLiH6xcsiTGKOljva5HDelCdBvunaWtUO/+CdKIgsdbQGbqc1aWmG6gr+ShQk4X3KzeAA91AFmkJOR6Jv69lUTm6Uo9AKs1JtuVZsOa1aoOmfApohqFuXsRBNXlg=
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organisation: dwenzel-github

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

before_script:
  - composer require typo3/minimal=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
- >
  if [[ "$COVERAGE" != "1" ]]; then
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  fi

- >
  if [[ "$COVERAGE" == "1" ]]; then
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c Tests/Build/UnitTests.xml Tests/Unit/ \
    --coverage-clover .Build/log/coverage/clover.xml \
    --log-junit .Build/log/junit.xml
    rm -rf .Build/vendor/ .Build/Web/ .Build/bin/
    sonar-scanner -Dproject.settings=.sonar-project.properties
  fi

after_success:
- >
  if [[ "$COVERAGE" == "1" ]]; then
    bash <(curl -s https://codecov.io/bash) -B $TRAVIS_BRANCH

    bin/test-reporter --stdout > codeclimate.json
    curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports
  fi
