services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DWenzel\T3events\:
    resource: '../Classes/*'

  DWenzel\T3events\Controller\Backend\ScheduleController:
    calls:
      - injectSession:
          - '@DWenzel\T3events\Session\Typo3BackendSession'

  DWenzel\T3events\Controller\EventController:
    arguments:
      $session: '@DWenzel\T3events\Session\Typo3Session'

  DWenzel\T3events\Controller\PerformanceController:
    arguments:
      $session: '@DWenzel\T3events\Session\Typo3Session'

  DWenzel\T3events\Service\FilterOptionsService:
    public: true

  DWenzel\T3events\Domain\Repository\TaskRepositoryInterface: '@DWenzel\T3events\Domain\Repository\TaskRepository'

  DWenzel\T3events\Service\TCA\ScheduleConfigurationService:
    public: true

  DWenzel\T3events\DataProvider\Form\EventPluginFormDataProvider:
    public: true

  DWenzel\T3events\Hooks\ItemsProcFunc:
    public: true
